# Generated by Django 4.0.4 on 2022-05-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_telegram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgaccount',
            old_name='telegram_nickname',
            new_name='tg_nickname',
        ),
    ]
