# Generated by Django 4.0.4 on 2022-05-05 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_telegram_nickname_tgaccount_tg_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tgaccount',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
