# Generated by Django 4.0.4 on 2022-05-05 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_can_invite_alter_tgaccount_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inviter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
