# Generated by Django 4.0.4 on 2022-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_googleauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleauth',
            name='is_installed',
            field=models.BooleanField(default=False),
        ),
    ]
