# Generated by Django 4.0.4 on 2022-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_googleauth_is_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line',
            field=models.IntegerField(default=1),
        ),
    ]
