# Generated by Django 4.0.4 on 2022-05-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Passive'), ('N', 'NotActive')], default='N', max_length=1),
        ),
    ]
