# Generated by Django 4.0.4 on 2022-05-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
