# Generated by Django 4.0.4 on 2022-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
