# Generated by Django 4.0.4 on 2022-05-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_permanent_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_deleted_ido',
            field=models.IntegerField(default=0),
        ),
    ]
