# Generated by Django 4.0.4 on 2022-05-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_count_deleted_ido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count_deleted_ido',
        ),
        migrations.AddField(
            model_name='user',
            name='hold',
            field=models.FloatField(default=0.0),
        ),
    ]
