# Generated by Django 4.0.4 on 2022-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_user_count_deleted_ido_user_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
