# Generated by Django 4.0.4 on 2022-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_user_referal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
