# Generated by Django 4.0.4 on 2022-05-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='referal_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
