# Generated by Django 4.0.4 on 2022-05-06 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, unique=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='Coin abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='CoinNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Coin network')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Exchange name')),
            ],
        ),
        migrations.AlterField(
            model_name='metamaskwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Metamask owner'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Transaction amount (volume)')),
                ('commission', models.FloatField(blank=True, null=True, verbose_name='Transaction commission')),
                ('address_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_address_from', to='core.address', verbose_name='Transaction source')),
                ('address_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_address_to', to='core.address', verbose_name='Transaction receiver')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Transaction coin')),
            ],
        ),
        migrations.AlterField(
            model_name='metamaskwallet',
            name='wallet_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Metamask address'),
        ),
    ]
