# Generated by Django 4.0.4 on 2022-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_metamaskwallet_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=4, unique=True, verbose_name='Coin abbreviation'),
        ),
        migrations.AlterField(
            model_name='coinnetwork',
            name='name',
            field=models.CharField(max_length=4, unique=True, verbose_name='Coin network'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Exchange name'),
        ),
    ]
