# Generated by Django 4.0.4 on 2022-05-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_metamaskwallet_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamaskwallet',
            name='wallet_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Metamask address'),
        ),
    ]
