# Generated by Django 4.0.4 on 2022-05-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0010_remove_ido_coin_network'),
        ('core', '0006_alter_metamaskwallet_wallet_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinNetwork',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='name',
        ),
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.CharField(max_length=128, null=True, verbose_name='Coin network'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='reference',
            field=models.CharField(max_length=128, null=True, verbose_name='Exchange reference'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
