# Generated by Django 4.0.4 on 2022-05-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_coinnetwork_remove_exchange_name_coin_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='network',
            field=models.CharField(max_length=128, unique=True, verbose_name='Coin network'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='reference',
            field=models.CharField(max_length=128, unique=True, verbose_name='Exchange reference'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
