# Generated by Django 4.0.4 on 2022-05-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adminwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.FloatField(default=0, verbose_name='Transaction commission'),
        ),
    ]
