# Generated by Django 4.0.4 on 2022-05-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_transaction_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='wallet_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Admin wallet address'),
        ),
    ]
