# Generated by Django 4.0.4 on 2022-05-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_adminwallet_balance_metamaskwallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metamaskwallet',
            name='balance',
        ),
    ]
