# Generated by Django 4.0.4 on 2022-05-12 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_remove_metamaskwallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Transaction amount (volume)')),
                ('avaliable', models.FloatField(default=0.0, verbose_name='Available coins')),
                ('received', models.FloatField(default=0.0, verbose_name='Received coins')),
                ('refund_allocation', models.FloatField(default=0.0, verbose_name='Refund allocation')),
                ('income_from_income', models.FloatField(default=0.0, verbose_name='Income from income')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Transaction coin')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_account', to=settings.AUTH_USER_MODEL, verbose_name='Invited account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_account', to=settings.AUTH_USER_MODEL, verbose_name='Owner account')),
            ],
        ),
    ]
