# Generated by Django 4.0.4 on 2022-05-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_accountbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='amount',
        ),
    ]
