# Generated by Django 4.0.4 on 2022-05-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_accountbalance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Balance'),
        ),
    ]
