# Generated by Django 4.0.4 on 2022-05-12 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_address_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_account', to=settings.AUTH_USER_MODEL, verbose_name='Invited account'),
        ),
    ]
