# Generated by Django 4.0.4 on 2022-05-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_accountbalance_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='balance',
        ),
    ]
