# Generated by Django 4.0.4 on 2022-05-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_address_main_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='owner_admin',
            field=models.BooleanField(default=False),
        ),
    ]
