# Generated by Django 4.0.4 on 2022-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_address_owner_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='decimal',
            field=models.FloatField(default=0, verbose_name='Admin wallet decimal'),
        ),
    ]
