# Generated by Django 4.0.4 on 2022-05-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_address_address_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coin'),
        ),
    ]
