# Generated by Django 4.0.4 on 2022-05-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_address_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='decimal',
            field=models.IntegerField(default=0, verbose_name='Admin wallet decimal'),
        ),
    ]
