# Generated by Django 4.0.4 on 2022-05-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_adminwallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True, verbose_name='Transaction amount (volume)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True, verbose_name='Transaction commission'),
        ),
    ]
