# Generated by Django 4.0.4 on 2022-05-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='cost_in_busd',
            field=models.FloatField(blank=True, null=True, verbose_name='BUSD cost'),
        ),
    ]
