# Generated by Django 4.0.4 on 2022-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_coin_cost_in_busd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=50, default=0, max_digits=100, null=True, verbose_name='Transaction commission'),
        ),
    ]
