# Generated by Django 4.0.4 on 2022-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_adminwallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
