# Generated by Django 4.0.4 on 2022-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_transaction_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.BooleanField(default=False),
        ),
    ]
