# Generated by Django 4.0.4 on 2022-05-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_transaction_commission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
