# Generated by Django 4.0.4 on 2022-05-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_delete_accountbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fill_up',
            field=models.BooleanField(default=True),
        ),
    ]
