# Generated by Django 4.0.4 on 2022-05-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_transaction_fill_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fill_up',
            field=models.BooleanField(default=False),
        ),
    ]
