# Generated by Django 4.0.4 on 2022-05-05 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name IDO')),
                ('description', models.TextField(verbose_name='Description IDO')),
                ('general_allocation', models.FloatField(verbose_name='General allocation')),
                ('person_allocation', models.FloatField(verbose_name='Person allocation')),
                ('buy_date', models.DateTimeField(verbose_name='Buy date')),
                ('tge', models.DateTimeField(verbose_name='Token Generating Event')),
                ('vesting', models.DateTimeField(verbose_name='Vesting')),
                ('smartcontract', models.CharField(max_length=128, null=True, verbose_name='Smart-contract address')),
                ('exchange', models.CharField(max_length=128, null=True, verbose_name='Reference to exchange')),
                ('coin_abbreviation', models.CharField(max_length=4, verbose_name='Coin abbreviation')),
                ('coin_network', models.CharField(max_length=64, verbose_name='Coin Network')),
                ('commission', models.FloatField(verbose_name='Platform commission (percents)')),
                ('telegram_acc', models.CharField(max_length=128, null=True, verbose_name='Telegram account')),
                ('twitter_acc', models.CharField(max_length=128, null=True, verbose_name='Twitter account')),
                ('discord_acc', models.CharField(max_length=128, null=True, verbose_name='Discord account')),
                ('site', models.CharField(max_length=128, null=True, verbose_name='Site')),
                ('white_paper', models.CharField(max_length=128, null=True, verbose_name='White paper')),
                ('without_pay', models.BooleanField(default=False)),
                ('charge_manually', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='ido/')),
            ],
        ),
        migrations.CreateModel(
            name='UsersOutOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.FloatField(verbose_name='Allocation')),
                ('ido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ido.ido', verbose_name='IDO')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ManuallyCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('coin', models.CharField(max_length=32, verbose_name='Coin')),
                ('ido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ido.ido', verbose_name='IDO')),
            ],
        ),
    ]
