# Generated by Django 4.0.4 on 2022-05-05 22:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ido', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManuallyCharges',
            new_name='ManuallyCharge',
        ),
        migrations.RenameModel(
            old_name='UsersOutOfOrder',
            new_name='UserOutOrder',
        ),
        migrations.AlterModelOptions(
            name='ido',
            options={'verbose_name_plural': 'IDO'},
        ),
        migrations.AlterModelOptions(
            name='useroutorder',
            options={'verbose_name_plural': 'UsersOutOrder'},
        ),
    ]
