# Generated by Django 4.0.4 on 2022-05-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0002_rename_manuallycharges_manuallycharge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroutorder',
            options={'verbose_name_plural': 'Users out order'},
        ),
    ]
