# Generated by Django 4.0.4 on 2022-05-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_coin_coinnetwork_exchange_and_more'),
        ('ido', '0004_alter_ido_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ido',
            name='coin_abbreviation',
        ),
        migrations.AddField(
            model_name='ido',
            name='coin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='coin_network',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coinnetwork', verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='commission',
            field=models.FloatField(verbose_name='Platform commission, percent'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='exchange',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exchange', verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='smartcontract',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Smartcontract address'),
        ),
        migrations.AlterField(
            model_name='manuallycharge',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='manuallycharge',
            name='ido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ido.ido', verbose_name='IDO'),
        ),
        migrations.AlterField(
            model_name='useroutorder',
            name='ido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ido.ido', verbose_name='IDO'),
        ),
    ]
