# Generated by Django 4.0.4 on 2022-05-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coin_name_alter_coinnetwork_name_and_more'),
        ('ido', '0005_remove_ido_coin_abbreviation_ido_coin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='coin_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coinnetwork', verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exchange', verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='smartcontract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Smartcontract address'),
        ),
    ]
