# Generated by Django 4.0.4 on 2022-05-06 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ido', '0006_alter_ido_coin_alter_ido_coin_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuallycharge',
            name='ido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ido.ido', verbose_name='IDO'),
        ),
        migrations.AlterField(
            model_name='useroutorder',
            name='ido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ido.ido', verbose_name='IDO'),
        ),
        migrations.CreateModel(
            name='IDOParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('ido', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ido.ido', verbose_name='IDO')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
