# Generated by Django 4.0.4 on 2022-05-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_metamaskwallet_wallet_address'),
        ('ido', '0008_idoparticipant_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='coin_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coinnetwork', verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exchange', verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='vesting',
            field=models.CharField(max_length=128, verbose_name='Vesting'),
        ),
    ]
