# Generated by Django 4.0.4 on 2022-05-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0009_alter_ido_coin_alter_ido_coin_network_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ido',
            name='coin_network',
        ),
    ]
