# Generated by Django 4.0.4 on 2022-05-10 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0010_remove_ido_coin_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoparticipant',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idoparticipant',
            name='queue_place',
            field=models.IntegerField(default=0, verbose_name='Queue place'),
        ),
    ]
