# Generated by Django 4.0.4 on 2022-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0011_idoparticipant_date_idoparticipant_queue_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoparticipant',
            name='queue_place',
            field=models.IntegerField(null=True, verbose_name='Queue place'),
        ),
    ]
