# Generated by Django 4.0.4 on 2022-05-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0013_alter_idoparticipant_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOutOrder',
        ),
    ]
