# Generated by Django 4.0.4 on 2022-05-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0014_delete_useroutorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idoparticipant',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='idoparticipant',
            name='queue_place',
        ),
    ]
