# Generated by Django 4.0.4 on 2022-05-11 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ido', '0015_remove_idoparticipant_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent', models.BooleanField(default=False, verbose_name='Permanent')),
                ('number', models.IntegerField(default=0, verbose_name='Number (place)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'number', 'permanent')},
            },
        ),
    ]
