# Generated by Django 4.0.4 on 2022-05-11 20:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ido', '0016_queueusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueueUsers',
            new_name='QueueUser',
        ),
    ]
