# Generated by Django 4.0.4 on 2022-05-11 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ido', '0018_alter_queueuser_unique_together_queueuser_ido_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queueuser',
            unique_together={('ido', 'user')},
        ),
    ]
