# Generated by Django 4.0.4 on 2022-05-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0019_alter_queueuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoparticipant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='queueuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
