# Generated by Django 4.0.4 on 2022-05-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_address_address_alter_address_unique_together'),
        ('ido', '0020_idoparticipant_is_active_queueuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='smartcontract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Smartcontract address'),
        ),
    ]
