# Generated by Django 4.0.4 on 2022-05-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0021_alter_ido_smartcontract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManuallyCharge',
        ),
    ]
