# Generated by Django 4.0.4 on 2022-05-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0022_delete_manuallycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoparticipant',
            name='income_from_income',
            field=models.FloatField(default=0.0, verbose_name='Income from income'),
        ),
        migrations.AddField(
            model_name='idoparticipant',
            name='refund_allocation',
            field=models.FloatField(default=0.0, verbose_name='Refund allocation'),
        ),
    ]
