# Generated by Django 4.0.4 on 2022-05-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_transaction_commission'),
        ('ido', '0023_idoparticipant_income_from_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='discord_acc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Discord account'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exchange', verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ido/'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='telegram_acc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram account'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='twitter_acc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Twitter account'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='white_paper',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='White paper'),
        ),
    ]
