# Generated by Django 4.0.4 on 2022-05-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0024_alter_ido_coin_alter_ido_discord_acc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='site',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Site'),
        ),
    ]
