# Generated by Django 4.0.4 on 2022-05-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0027_alter_ido_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ido/'),
        ),
    ]
