# Generated by Django 4.0.4 on 2022-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='referal_profit',
            field=models.FloatField(null=True, verbose_name='referal IDO income percent'),
        ),
    ]
