# Generated by Django 4.0.4 on 2022-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_vipuser_referal_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='referal_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='referal IDO income percent'),
        ),
    ]
